# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controls.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_C(object):
    def setupUi(self, C):
        C.setObjectName("C")
        C.setEnabled(True)
        C.resize(1092, 892)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        C.setFont(font)
        #C.setStyleSheet("background-color: white")
        C.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        C.setAutoFillBackground(True)
        
        self.centralwidget = QtWidgets.QWidget(C)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        
 
        self.tableWidget.setGeometry(QtCore.QRect(35, 621, 961, 211))
        self.tableWidget.setObjectName("tableWidget")

        self.pushButton_Advanced_UI = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Advanced_UI.setGeometry(QtCore.QRect(900, 50, 121, 41))
        self.pushButton_Advanced_UI.setObjectName("pushButton_Advanced_UI")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 590, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 590, 41, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(870, 580, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(160, 130, 151, 401))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget_5 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem, 0, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_14.addWidget(self.label_30, 0, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_14.addWidget(self.line_12, 1, 0, 1, 4)
        self.label_ROP15 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_ROP15.setFont(font)
        self.label_ROP15.setObjectName("label_ROP15")
        self.gridLayout_14.addWidget(self.label_ROP15, 0, 3, 1, 1)
        self.layoutWidget_6 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_15.addWidget(self.label_32, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem1, 0, 1, 1, 1)
        self.label_ROP3 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_ROP3.setFont(font)
        self.label_ROP3.setObjectName("label_ROP3")
        self.gridLayout_15.addWidget(self.label_ROP3, 0, 2, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.layoutWidget_6)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_15.addWidget(self.line_13, 1, 0, 1, 3)
        self.layoutWidget_7 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_16.addWidget(self.label_34, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem2, 0, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.layoutWidget_7)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_16.addWidget(self.line_14, 1, 0, 1, 3)
        self.label_MSE = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_MSE.setFont(font)
        self.label_MSE.setObjectName("label_MSE")
        self.gridLayout_16.addWidget(self.label_MSE, 0, 2, 1, 1)
        self.layoutWidget_8 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.layoutWidget_8)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem3, 0, 1, 1, 1)
        self.label_UCS = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_UCS.setFont(font)
        self.label_UCS.setObjectName("label_UCS")
        self.gridLayout_17.addWidget(self.label_UCS, 0, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_17.addWidget(self.label_37, 0, 0, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.layoutWidget_8)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_17.addWidget(self.line_15, 1, 0, 1, 3)
        self.layoutWidget_9 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.layoutWidget_9)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem4, 0, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.layoutWidget_9)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_18.addWidget(self.line_16, 1, 0, 1, 3)
        self.label_Torque = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Torque.setFont(font)
        self.label_Torque.setObjectName("label_Torque")
        self.gridLayout_18.addWidget(self.label_Torque, 0, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_18.addWidget(self.label_39, 0, 0, 1, 1)
        self.layoutWidget_10 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.layoutWidget_10)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem5, 0, 1, 1, 1)
        self.label_WOB = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_WOB.setFont(font)
        self.label_WOB.setObjectName("label_WOB")
        self.gridLayout_19.addWidget(self.label_WOB, 0, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_19.addWidget(self.label_41, 0, 0, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.layoutWidget_10)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_19.addWidget(self.line_17, 1, 0, 1, 3)
        self.layoutWidget_11 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.layoutWidget_11)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_20.addWidget(self.label_43, 0, 0, 1, 1)
        self.label_d_exponent = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_d_exponent.setFont(font)
        self.label_d_exponent.setObjectName("label_d_exponent")
        self.gridLayout_20.addWidget(self.label_d_exponent, 0, 2, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.layoutWidget_11)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_20.addWidget(self.line_18, 1, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem6, 0, 1, 1, 1)
        self.layoutWidget_12 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.layoutWidget_12)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.line_19 = QtWidgets.QFrame(self.layoutWidget_12)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_21.addWidget(self.line_19, 1, 0, 1, 3)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_21.addWidget(self.label_45, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem7, 0, 1, 1, 1)
        self.label_Height = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Height.setFont(font)
        self.label_Height.setObjectName("label_Height")
        self.gridLayout_21.addWidget(self.label_Height, 0, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(350, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(550, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.layoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_13.setGeometry(QtCore.QRect(540, 130, 181, 221))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.layoutWidget_13)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_Moving = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_Moving.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Moving.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Moving.setWordWrap(False)
        self.label_Moving.setObjectName("label_Moving")
        self.gridLayout_24.addWidget(self.label_Moving, 1, 0, 1, 1)
        self.label_Brake_Open = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_Brake_Open.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Brake_Open.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Brake_Open.setWordWrap(False)
        self.label_Brake_Open.setObjectName("label_Brake_Open")
        self.gridLayout_24.addWidget(self.label_Brake_Open, 2, 0, 1, 1)
        self.label_Start = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_Start.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Start.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Start.setWordWrap(False)
        self.label_Start.setObjectName("label_Start")
        self.gridLayout_24.addWidget(self.label_Start, 3, 0, 1, 1)
        self.label_Brake_Closed = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_Brake_Closed.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Brake_Closed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Brake_Closed.setWordWrap(False)
        self.label_Brake_Closed.setObjectName("label_Brake_Closed")
        self.gridLayout_24.addWidget(self.label_Brake_Closed, 2, 1, 1, 1)
        self.label_WOB_Ctrl = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_WOB_Ctrl.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_WOB_Ctrl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_WOB_Ctrl.setWordWrap(False)
        self.label_WOB_Ctrl.setObjectName("label_WOB_Ctrl")
        self.gridLayout_24.addWidget(self.label_WOB_Ctrl, 0, 1, 1, 1)
        self.label_Stopped = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_Stopped.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Stopped.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Stopped.setStyleSheet("background-color: green")
        self.label_Stopped.setWordWrap(False)
        self.label_Stopped.setObjectName("label_Stopped")
        self.gridLayout_24.addWidget(self.label_Stopped, 0, 0, 1, 1)
        self.label_Calibrationg = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_Calibrationg.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Calibrationg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Calibrationg.setWordWrap(False)
        self.label_Calibrationg.setObjectName("label_Calibrationg")
        self.gridLayout_24.addWidget(self.label_Calibrationg, 1, 1, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.centralwidget)
        self.label_80.setGeometry(QtCore.QRect(760, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.layoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_14.setGeometry(QtCore.QRect(750, 180, 131, 101))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.layoutWidget_14)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_Stopped_2 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_Stopped_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Stopped_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Stopped_2.setStyleSheet("background-color: green")
        self.label_Stopped_2.setWordWrap(False)
        self.label_Stopped_2.setObjectName("label_Stopped_2")
        self.gridLayout_25.addWidget(self.label_Stopped_2, 0, 1, 1, 1)
        self.label_Rotating = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_Rotating.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Rotating.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Rotating.setWordWrap(False)
        self.label_Rotating.setObjectName("label_Rotating")
        self.gridLayout_25.addWidget(self.label_Rotating, 0, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(500, 370, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_84 = QtWidgets.QLabel(self.centralwidget)
        self.label_84.setGeometry(QtCore.QRect(960, 430, 47, 13))
        self.label_84.setObjectName("label_84")
        self.spinBox_RPM = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_RPM.setRange(0,1500)
        self.spinBox_RPM.setGeometry(QtCore.QRect(960, 460, 62, 22))
        self.spinBox_RPM.setObjectName("doubleSpinBox_RPM")
        self.pushButton_RPM_Enter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_RPM_Enter.setGeometry(QtCore.QRect(960, 490, 75, 23))
        self.pushButton_RPM_Enter.setObjectName("pushButton_RPM_Enter")
        self.pushButton_PID_Enter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PID_Enter.setGeometry(QtCore.QRect(750, 570, 75, 23))
        self.pushButton_PID_Enter.setObjectName("pushButton_PID_Enter")

        self.pushButton_Hoistiong_Enter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Hoistiong_Enter.setGeometry(QtCore.QRect(650, 585, 75, 23))
        self.pushButton_Hoistiong_Enter.setObjectName("pushButton_Hoistiong_Enter")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(650, 400, 87, 176))
        self.widget.setObjectName("widget")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_85 = QtWidgets.QLabel(self.widget)
        self.label_85.setObjectName("label_85")
        self.gridLayout_27.addWidget(self.label_85, 15, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.widget)
        self.label_82.setObjectName("label_82")
        self.gridLayout_27.addWidget(self.label_82, 10, 0, 1, 1)
        self.spinBox_Stepper_Delay = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinBox_Stepper_Delay.setRange(0,500)
        self.spinBox_Stepper_Delay.setObjectName("spinBox_Stepper_Delay")
        self.gridLayout_27.addWidget(self.spinBox_Stepper_Delay, 14, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.widget)
        self.label_83.setObjectName("label_83")
        self.gridLayout_27.addWidget(self.label_83, 13, 0, 1, 1)
        self.comboBox_Actuator = QtWidgets.QComboBox(self.widget)
        self.comboBox_Actuator.setObjectName("comboBox_Actuator")
        self.gridLayout_27.addWidget(self.comboBox_Actuator, 4, 0, 1, 1)
        self.doubleSpinBox_Distance = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_Distance.setObjectName("doubleSpinBox_Distance")
        self.gridLayout_27.addWidget(self.doubleSpinBox_Distance, 11, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.widget)
        self.label_81.setObjectName("label_81")
        self.gridLayout_27.addWidget(self.label_81, 3, 0, 1, 1)
        self.comboBox_Direction = QtWidgets.QComboBox(self.widget)
        self.comboBox_Direction.setObjectName("comboBox_Direction")
        self.gridLayout_27.addWidget(self.comboBox_Direction, 16, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(430, 400, 208, 118))
        self.widget1.setObjectName("widget1")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.pushButton_Open_Brake = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Open_Brake.setObjectName("pushButton_Open_Brake")
        self.gridLayout_26.addWidget(self.pushButton_Open_Brake, 0, 0, 1, 1)
        self.pushButton_Rese_WOB = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Rese_WOB.setObjectName("pushButton_Rese_WOB")
        self.gridLayout_26.addWidget(self.pushButton_Rese_WOB, 0, 1, 1, 1)
        self.pushButton_Stop_Brake = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Stop_Brake.setObjectName("pushButton_Stop_Brake")
        self.gridLayout_26.addWidget(self.pushButton_Stop_Brake, 1, 0, 2, 1)
        self.pushButton_WOB_Ctrl = QtWidgets.QPushButton(self.widget1)
        self.pushButton_WOB_Ctrl.setObjectName("pushButton_WOB_Ctrl")
        self.gridLayout_26.addWidget(self.pushButton_WOB_Ctrl, 1, 1, 1, 1)
        self.pushButton_Reset_Stepper_Pos = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Reset_Stepper_Pos.setAcceptDrops(False)
        self.pushButton_Reset_Stepper_Pos.setObjectName("pushButton_Reset_Stepper_Pos")
        self.gridLayout_26.addWidget(self.pushButton_Reset_Stepper_Pos, 2, 1, 2, 1)
        self.pushButton_Telementary = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Telementary.setObjectName("pushButton_Telementary")
        self.gridLayout_26.addWidget(self.pushButton_Telementary, 3, 0, 1, 1)
        self.pushButton_Stop_Hoisting = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Stop_Hoisting.setObjectName("pushButton_Stop_Hoisting")
        self.gridLayout_26.addWidget(self.pushButton_Stop_Hoisting, 4, 0, 1, 1)

        self.pushButton_Calibrate = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Calibrate.setObjectName("pushButton_Calibrate")
        self.gridLayout_26.addWidget(self.pushButton_Calibrate, 5, 0, 1, 1)


        self.pushButton_Reset_Hook_Load = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Reset_Hook_Load.setObjectName("pushButton_Reset_Hook_Load")
        self.gridLayout_26.addWidget(self.pushButton_Reset_Hook_Load, 4, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(340, 130, 151, 221))
        self.widget2.setObjectName("widget2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Pack_Off = QtWidgets.QLabel(self.widget2)
        self.label_Pack_Off.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Pack_Off.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Pack_Off.setWordWrap(False)
        self.label_Pack_Off.setObjectName("label_Pack_Off")
        self.gridLayout.addWidget(self.label_Pack_Off, 3, 1, 1, 1)
        self.label_Starting = QtWidgets.QLabel(self.widget2)
        self.label_Starting.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Starting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Starting.setWordWrap(False)
        self.label_Starting.setObjectName("label_Starting")
        self.gridLayout.addWidget(self.label_Starting, 1, 0, 1, 1)
        self.label_LEAK = QtWidgets.QLabel(self.widget2)
        self.label_LEAK.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_LEAK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_LEAK.setWordWrap(False)
        self.label_LEAK.setObjectName("label_LEAK")
        self.gridLayout.addWidget(self.label_LEAK, 2, 0, 1, 1)
        self.label_END = QtWidgets.QLabel(self.widget2)
        self.label_END.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_END.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_END.setWordWrap(False)
        self.label_END.setObjectName("label_END")
        self.gridLayout.addWidget(self.label_END, 3, 0, 1, 1)
        self.label_Monitor = QtWidgets.QLabel(self.widget2)
        self.label_Monitor.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Monitor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Monitor.setWordWrap(False)
        self.label_Monitor.setObjectName("label_Monitor")
        self.gridLayout.addWidget(self.label_Monitor, 2, 1, 1, 1)
        self.label_Pump_Off = QtWidgets.QLabel(self.widget2)
        self.label_Pump_Off.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Pump_Off.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Pump_Off.setWordWrap(False)
        self.label_Pump_Off.setObjectName("label_Pump_Off")
        self.gridLayout.addWidget(self.label_Pump_Off, 0, 1, 1, 1)
        self.label_Pump_On = QtWidgets.QLabel(self.widget2)
        self.label_Pump_On.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Pump_On.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Pump_On.setWordWrap(False)
        self.label_Pump_On.setObjectName("label_Pump_On")
        self.gridLayout.addWidget(self.label_Pump_On, 0, 0, 1, 1)
        self.label_OFF = QtWidgets.QLabel(self.widget2)
        self.label_OFF.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_OFF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_OFF.setWordWrap(False)
        self.label_OFF.setObjectName("label_OFF")
        self.gridLayout.addWidget(self.label_OFF, 1, 1, 1, 1)
        self.splitter_6 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_6.setGeometry(QtCore.QRect(750, 390, 71, 171))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.label_86 = QtWidgets.QLabel(self.splitter_6)
        self.label_86.setObjectName("label_86")
        self.doubleSpinBox_WOB = QtWidgets.QDoubleSpinBox(self.splitter_6)
        self.doubleSpinBox_WOB.setObjectName("doubleSpinBox_WOB")
        self.label_89 = QtWidgets.QLabel(self.splitter_6)
        self.label_89.setObjectName("label_89")
        self.doubleSpinBox_Kp = QtWidgets.QDoubleSpinBox(self.splitter_6)
        self.doubleSpinBox_Kp.setObjectName("doubleSpinBox_Kp")
        self.label_88 = QtWidgets.QLabel(self.splitter_6)
        self.label_88.setObjectName("label_88")
        self.doubleSpinBox_Ki = QtWidgets.QDoubleSpinBox(self.splitter_6)
        self.doubleSpinBox_Ki.setObjectName("doubleSpinBox_Ki")
        self.label_87 = QtWidgets.QLabel(self.splitter_6)
        self.label_87.setObjectName("label_87")
        self.doubleSpinBox_Kd = QtWidgets.QDoubleSpinBox(self.splitter_6)
        self.doubleSpinBox_Kd.setObjectName("doubleSpinBox_Kd")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setGeometry(QtCore.QRect(850, 400, 91, 121))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.pushButton_Stop_Rotation = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_Stop_Rotation.setObjectName("pushButton_Stop_Rotation")
        self.pushButton_Reset_WOB = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_Reset_WOB.setObjectName("pushButton_Reset_WOB")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(10, 130, 131, 401))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.widget3 = QtWidgets.QWidget(self.splitter_2)
        self.widget3.setObjectName("widget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.widget3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 0, 1, 4)
        self.label_RPM = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_RPM.setFont(font)
        self.label_RPM.setObjectName("label_RPM")
        self.gridLayout_3.addWidget(self.label_RPM, 0, 3, 1, 1)
        self.widget4 = QtWidgets.QWidget(self.splitter_2)
        self.widget4.setObjectName("widget4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        self.label_Torque_Motor = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Torque_Motor.setFont(font)
        self.label_Torque_Motor.setObjectName("label_Torque_Motor")
        self.gridLayout_4.addWidget(self.label_Torque_Motor, 0, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.widget4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 3)
        self.widget5 = QtWidgets.QWidget(self.splitter_2)
        self.widget5.setObjectName("widget5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 1, 0, 1, 3)
        self.label_Torque_Sensor = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Torque_Sensor.setFont(font)
        self.label_Torque_Sensor.setObjectName("label_Torque_Sensor")
        self.gridLayout_5.addWidget(self.label_Torque_Sensor, 0, 2, 1, 1)
        self.widget6 = QtWidgets.QWidget(self.splitter_2)
        self.widget6.setObjectName("widget6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 0, 1, 1, 1)
        self.label_Pressure = QtWidgets.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Pressure.setFont(font)
        self.label_Pressure.setObjectName("label_Pressure")
        self.gridLayout_6.addWidget(self.label_Pressure, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 1, 0, 1, 3)
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem12, 0, 1, 1, 1)
        self.label_Z1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Z1.setFont(font)
        self.label_Z1.setObjectName("label_Z1")
        self.gridLayout_8.addWidget(self.label_Z1, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_8.addWidget(self.line_6, 1, 0, 1, 3)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem13, 0, 1, 1, 1)
        self.label_Z2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Z2.setFont(font)
        self.label_Z2.setObjectName("label_Z2")
        self.gridLayout_10.addWidget(self.label_Z2, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_10.addWidget(self.line_8, 1, 0, 1, 3)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem14, 0, 1, 1, 1)
        self.label_Z3 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Z3.setFont(font)
        self.label_Z3.setObjectName("label_Z3")
        self.gridLayout_12.addWidget(self.label_Z3, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 0, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_12.addWidget(self.line_10, 1, 0, 1, 3)
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem15, 0, 1, 1, 1)
        self.label_SumZ = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_SumZ.setFont(font)
        self.label_SumZ.setObjectName("label_SumZ")
        self.gridLayout_13.addWidget(self.label_SumZ, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_13.addWidget(self.label_29, 0, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_13.addWidget(self.line_11, 1, 0, 1, 3)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(410, 50, 341, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_Start_Drilling = QtWidgets.QPushButton(self.splitter)
        self.pushButton_Start_Drilling.setObjectName("pushButton_Start_Drilling")
        self.pushButton_Stop_Drilling = QtWidgets.QPushButton(self.splitter)
        self.pushButton_Stop_Drilling.setObjectName("pushButton_Stop_Drilling")
        self.widget7 = QtWidgets.QWidget(self.centralwidget)
        self.widget7.setGeometry(QtCore.QRect(11, 50, 365, 44))
        self.widget7.setObjectName("widget7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_Hoisting = QtWidgets.QComboBox(self.widget7)
        self.comboBox_Hoisting.setObjectName("comboBox_Hoisting")
        self.gridLayout_2.addWidget(self.comboBox_Hoisting, 1, 0, 1, 1)
        self.comboBox_Circulation = QtWidgets.QComboBox(self.widget7)
        self.comboBox_Circulation.setObjectName("comboBox_Circulation")
        self.gridLayout_2.addWidget(self.comboBox_Circulation, 1, 1, 1, 1)
        self.comboBox_Rotation = QtWidgets.QComboBox(self.widget7)
        self.comboBox_Rotation.setObjectName("comboBox_Rotation")
        self.gridLayout_2.addWidget(self.comboBox_Rotation, 1, 2, 1, 1)
        self.pushButton_OpenPorts = QtWidgets.QPushButton(self.widget7)
        self.pushButton_OpenPorts.setObjectName("pushButton_OpenPorts")
        self.gridLayout_2.addWidget(self.pushButton_OpenPorts, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setGeometry(QtCore.QRect(330, 400, 75, 111))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.pushButton_Start_Pump = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_Start_Pump.setObjectName("pushButton_Start_Pump")
        self.pushButton_Stop_Pump = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_Stop_Pump.setObjectName("pushButton_Stop_Pump")
        self.tableWidget.raise_()
        self.comboBox_Circulation.raise_()
        self.comboBox_Rotation.raise_()
        self.comboBox_Hoisting.raise_()
        self.pushButton_OpenPorts.raise_()
        self.pushButton_Advanced_UI.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton_Start_Drilling.raise_()
        self.pushButton_Stop_Drilling.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_RPM.raise_()
        self.label_10.raise_()
        self.label_Torque_Motor.raise_()
        self.label_Torque_Sensor.raise_()
        self.label_13.raise_()
        self.label_Pressure.raise_()
        self.label_15.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget_2.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_4.raise_()
        self.splitter_3.raise_()
        self.label_Pump_On.raise_()
        self.label_Pump_Off.raise_()
        self.label_Starting.raise_()
        self.label_OFF.raise_()
        self.label_LEAK.raise_()
        self.label_Monitor.raise_()
        self.label_END.raise_()
        self.label_Pack_Off.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.layoutWidget_13.raise_()
        self.label_80.raise_()
        self.layoutWidget_14.raise_()
        self.pushButton_Stop_Pump.raise_()
        self.pushButton_Open_Brake.raise_()
        self.pushButton_Stop_Brake.raise_()
        self.pushButton_Telementary.raise_()
        self.pushButton_Rese_WOB.raise_()
        self.pushButton_WOB_Ctrl.raise_()
        self.pushButton_Reset_WOB.raise_()
        self.pushButton_Reset_Stepper_Pos.raise_()
        self.pushButton_Reset_Hook_Load.raise_()
        self.pushButton_Stop_Rotation.raise_()
        self.label_64.raise_()
        self.label_81.raise_()
        self.comboBox_Actuator.raise_()
        self.label_82.raise_()
        self.doubleSpinBox_Distance.raise_()
        self.label_83.raise_()
        self.spinBox_Stepper_Delay.raise_()
        self.label_84.raise_()
        self.spinBox_RPM.raise_()
        self.pushButton_RPM_Enter.raise_()
        self.label_86.raise_()
        self.label_87.raise_()
        self.label_88.raise_()
        self.label_89.raise_()
        self.doubleSpinBox_WOB.raise_()
        self.doubleSpinBox_Kp.raise_()
        self.doubleSpinBox_Ki.raise_()
        self.doubleSpinBox_Kd.raise_()
        self.pushButton_Hoistiong_Enter.raise_()
        self.pushButton_PID_Enter.raise_()
       # C.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(C)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 20))
        self.menubar.setObjectName("menubar")
       # C.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(C)
        self.statusbar.setObjectName("statusbar")
        #C.setStatusBar(self.statusbar)

        self.retranslateUi(C)
        QtCore.QMetaObject.connectSlotsByName(C)

    def retranslateUi(self, C):
        _translate = QtCore.QCoreApplication.translate
        C.setWindowTitle(_translate("C", "MainWindow"))
        self.pushButton_Advanced_UI.setText(_translate("C", "Advanced UI"))
        self.label.setText(_translate("C", "Incident/Occurance"))
        self.label_2.setText(_translate("C", "Time"))
        self.label_3.setText(_translate("C", "# of occurances"))
        self.label_4.setText(_translate("C", "Drillbotics Control Interface"))
        self.label_30.setText(_translate("C", "ROP (15s)"))
        self.label_ROP15.setText(_translate("C", "0"))
        self.label_32.setText(_translate("C", "ROP (3m)"))
        self.label_ROP3.setText(_translate("C", "0"))
        self.label_34.setText(_translate("C", "Q (LPM)")) #Change this
        self.label_MSE.setText(_translate("C", "0"))
        self.label_UCS.setText(_translate("C", "0"))
        self.label_37.setText(_translate("C", "UCS (MPa)"))
        self.label_Torque.setText(_translate("C", "0"))
        self.label_39.setText(_translate("C", "Torque Bit (Nm)"))
        self.label_WOB.setText(_translate("C", "0"))
        self.label_41.setText(_translate("C", "WOB (kg)"))
        self.label_43.setText(_translate("C", "d-Eexponenet"))
        self.label_d_exponent.setText(_translate("C", "0"))
        self.label_45.setText(_translate("C", "Height"))
        self.label_Height.setText(_translate("C", "0"))
        self.label_54.setText(_translate("C", "Circulation system"))
        self.label_55.setText(_translate("C", "Hoisting system"))
        self.label_Moving.setText(_translate("C", "Moving"))
        self.label_Brake_Open.setText(_translate("C", "Brake Open"))
        self.label_Start.setText(_translate("C", "Start"))
        self.label_Brake_Closed.setText(_translate("C", "Brake Closed"))
        self.label_WOB_Ctrl.setText(_translate("C", "WOB Control"))
        self.label_Stopped.setText(_translate("C", "Stopped"))
        self.label_Calibrationg.setText(_translate("C", "Calibrating"))
        self.label_80.setText(_translate("C", "Rotation System"))
        self.label_Stopped_2.setText(_translate("C", "Stopped"))
        self.label_Rotating.setText(_translate("C", "Rotating"))
        self.label_64.setText(_translate("C", "Controls"))
        self.label_84.setText(_translate("C", "RPM"))
        self.pushButton_RPM_Enter.setText(_translate("C", "Enter"))
        self.pushButton_Hoistiong_Enter.setText(_translate("C", "Enter"))
        self.pushButton_PID_Enter.setText(_translate("C","Enter"))
        self.label_85.setText(_translate("C", "Direction"))
        self.label_82.setText(_translate("C", "Distance (mm)"))
        self.label_83.setText(_translate("C", "Stepper delay"))
        self.label_81.setText(_translate("C", "Acuator"))
        self.pushButton_Open_Brake.setText(_translate("C", "Open Brake"))
        self.pushButton_Rese_WOB.setText(_translate("C", "Reset WOB"))
        self.pushButton_Stop_Brake.setText(_translate("C", "Stop Brake"))
        self.pushButton_WOB_Ctrl.setText(_translate("C", "WOB Control"))
        self.pushButton_Reset_Stepper_Pos.setText(_translate("C", "Reset Stepper Pos."))
        self.pushButton_Telementary.setText(_translate("C", "Telementary"))
        self.pushButton_Stop_Hoisting.setText(_translate("C", "Stop Hoisting"))
        self.pushButton_Calibrate.setText(_translate("C", "Calibrate"))
        self.pushButton_Reset_Hook_Load.setText(_translate("C", "Reset Hook Load"))
        self.label_Pack_Off.setText(_translate("C", "Pack Off"))
        self.label_Starting.setText(_translate("C", "Starting"))
        self.label_LEAK.setText(_translate("C", "LEAK"))
        self.label_END.setText(_translate("C", "END"))
        self.label_Monitor.setText(_translate("C", "Monitor"))
        self.label_Pump_Off.setText(_translate("C", "Pump Off"))
        self.label_Pump_On.setText(_translate("C", "Pump On"))
        self.label_OFF.setText(_translate("C", "OFF"))
        self.label_86.setText(_translate("C", "WOB"))
        self.label_89.setText(_translate("C", "Kp"))
        self.label_88.setText(_translate("C", "Ki"))
        self.label_87.setText(_translate("C", "Kd"))
        self.pushButton_Stop_Rotation.setText(_translate("C", "Stop Rotation"))
        self.pushButton_Reset_WOB.setText(_translate("C", "Reset ROP"))
        self.label_8.setText(_translate("C", "RPM"))
        self.label_RPM.setText(_translate("C", "0"))
        self.label_10.setText(_translate("C", "Torque Motor"))
        self.label_Torque_Motor.setText(_translate("C", "0"))
        self.label_13.setText(_translate("C", "Torque Sensor"))
        self.label_Torque_Sensor.setText(_translate("C", "0"))
        self.label_Pressure.setText(_translate("C", "0"))
        self.label_15.setText(_translate("C", "Pressure"))
        self.label_Z1.setText(_translate("C", "0"))
        self.label_19.setText(_translate("C", "Z1"))
        self.label_Z2.setText(_translate("C", "0"))
        self.label_23.setText(_translate("C", "Z2"))
        self.label_Z3.setText(_translate("C", "0"))
        self.label_27.setText(_translate("C", "Z3"))
        self.label_SumZ.setText(_translate("C", "0"))
        self.label_29.setText(_translate("C", "∑Z"))
        self.pushButton_Start_Drilling.setText(_translate("C", "Start Autonomous Drilling"))
        self.pushButton_Stop_Drilling.setText(_translate("C", "Stop Autonomous Drilling"))
        self.label_5.setText(_translate("C", "Hoisting Port"))
        self.pushButton_OpenPorts.setText(_translate("C", "Open"))
        self.label_6.setText(_translate("C", "Circulation Port"))
        self.label_7.setText(_translate("C", "Rotation Port"))
        self.pushButton_Start_Pump.setText(_translate("C", "Start Pump"))
        self.pushButton_Stop_Pump.setText(_translate("C", "Stop Pump"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    C = QtWidgets.QMainWindow()
    ui = Ui_C()
    ui.setupUi(C)
    C.show()
    sys.exit(app.exec_())

