# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualizationGUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
#from qopenglwidget import QOpenGLWidget
from PyQt5.QtWidgets import QApplication, QMainWindow, QOpenGLWidget, QHBoxLayout, QWidget, QLabel


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(3859, 2160)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.graphicsView_adv_RPMWOB = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_RPMWOB.setGeometry(QtCore.QRect(40, 1050, 971, 581))
        self.graphicsView_adv_RPMWOB.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.graphicsView_adv_RPMWOB.setObjectName(_fromUtf8("grapgicsView_adv_RPMWOB"))

        self.checkBox_adv_accessLiveFeed = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_adv_accessLiveFeed.setGeometry(QtCore.QRect(310, 980, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_adv_accessLiveFeed.setFont(font)
        self.checkBox_adv_accessLiveFeed.setObjectName(_fromUtf8("checkBox_adv_accessLiveFeed"))
        self.graphicsView_adv_ROPStep = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_ROPStep.setGeometry(QtCore.QRect(40, 1657, 971, 191))
        self.graphicsView_adv_ROPStep.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.graphicsView_adv_ROPStep.setObjectName(_fromUtf8("graphicsView_adv_ROPStep"))

        self.graphicsView_adv_MSEStep = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_MSEStep.setGeometry(QtCore.QRect(40, 1850, 971, 191))
        self.graphicsView_adv_MSEStep.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.graphicsView_adv_MSEStep.setObjectName(_fromUtf8("graphicsView_adv_MSEStep"))

        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 920, 3721, 20))
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 970, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 0, 21, 2061))
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(9, 2050, 3721, 21))
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(3720, 0, 21, 2061))
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, -3, 3721, 20))
        self.line_6.setLineWidth(5)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.dial_adv_ROP = QtGui.QDial(self.centralwidget)
        self.dial_adv_ROP.setGeometry(QtCore.QRect(-110, 190, 741, 521))
        self.dial_adv_ROP.setMinimum(0)
        self.dial_adv_ROP.setMaximum(100)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dial_adv_ROP.setFont(font)
        self.dial_adv_ROP.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_ROP.setObjectName(_fromUtf8("dial_adv_ROP"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 10, 421, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.dial_adv_flowRate = QtGui.QDial(self.centralwidget)
        self.dial_adv_flowRate.setGeometry(QtCore.QRect(2020, 510, 581, 331))
        self.dial_adv_flowRate.setMinimum(0)
        self.dial_adv_flowRate.setMaximum(200)
        self.dial_adv_flowRate.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_flowRate.setObjectName(_fromUtf8("dial_adv_flowRate"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1400, 470, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(2200, 469, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(990, 470, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1770, 470, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(821, 5, 21, 921))
        self.line_7.setLineWidth(5)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.lcdNumber_adv_AvgROP = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_adv_AvgROP.setGeometry(QtCore.QRect(2550, 450, 241, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_adv_AvgROP.setFont(font)
        self.lcdNumber_adv_AvgROP.setObjectName(_fromUtf8("lcdNumber_adv_AvgROP"))
        self.lcdNumber_adv_Duration = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_adv_Duration.setGeometry(QtCore.QRect(2550, 260, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_adv_Duration.setFont(font)
        self.lcdNumber_adv_Duration.setObjectName(_fromUtf8("lcdNumber_adv_Duration"))
        self.lcdNumber_WellTVD = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_WellTVD.setGeometry(QtCore.QRect(2550, 70, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_WellTVD.setFont(font)
        self.lcdNumber_WellTVD.setObjectName(_fromUtf8("lcdNumber_WellTVD"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(2552, 390, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(2550, 20, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(2552, 200, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(80, 655, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(390, 650, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(230, 160, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(1450, 510, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(930, 810, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(1880, 510, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(1150, 810, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(2298, 505, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(1030, 510, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.progressBar_adv_axialVib = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_adv_axialVib.setGeometry(QtCore.QRect(1690, 850, 381, 31))
        self.progressBar_adv_axialVib.setRange(-500,500)
        #self.progressBar_adv_axialVib.setProperty("value", 24)
        self.progressBar_adv_axialVib.setObjectName(_fromUtf8("progressBar_adv_axialVib"))
        self.progressBar_adv_flowRate = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_adv_flowRate.setGeometry(QtCore.QRect(2110, 850, 381, 31))
        self.progressBar_adv_flowRate.setRange(0,200)
        #self.progressBar_adv_flowRate.setProperty("value", 24)
        self.progressBar_adv_flowRate.setObjectName(_fromUtf8("progressBar_adv_flowRate"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(1100, 950, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(2830, 10, 881, 831))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0,0,0,0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_adv_Velocity = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_Velocity.setFont(font)
        self.label_adv_Velocity.setObjectName(_fromUtf8("label_adv_Velocity"))
        self.gridLayout_5.addWidget(self.label_adv_Velocity, 4, 2, 1, 1)
        self.label_adv_stepCounter = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_stepCounter.setFont(font)
        self.label_adv_stepCounter.setObjectName(_fromUtf8("label_adv_stepCounter"))
        self.gridLayout_5.addWidget(self.label_adv_stepCounter, 20, 2, 1, 1)
        self.line_18 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_18.setFont(font)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.gridLayout_5.addWidget(self.line_18, 21, 0, 1, 3)
        self.label_adv_flowRate = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_flowRate.setFont(font)
        self.label_adv_flowRate.setObjectName(_fromUtf8("label_adv_flowRate"))
        self.gridLayout_5.addWidget(self.label_adv_flowRate, 16, 2, 1, 1)
        self.line_21 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_21.setFont(font)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.gridLayout_5.addWidget(self.line_21, 17, 0, 1, 3)
        self.label_adv_Pressure = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_Pressure.setFont(font)
        self.label_adv_Pressure.setObjectName(_fromUtf8("label_adv_Pressure"))
        self.gridLayout_5.addWidget(self.label_adv_Pressure, 14, 2, 1, 1)
        self.label_51 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_5.addWidget(self.label_51, 18, 0, 1, 1)
        self.label_adv_Height = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_Height.setFont(font)
        self.label_adv_Height.setObjectName(_fromUtf8("label_adv_Height"))
        self.gridLayout_5.addWidget(self.label_adv_Height, 18, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_5.addWidget(self.label_52, 0, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_5.addWidget(self.label_50, 20, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_5.addWidget(self.label_49, 16, 0, 1, 1)
        self.line_17 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_17.setFont(font)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.gridLayout_5.addWidget(self.line_17, 15, 0, 1, 3)
        self.line_19 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_19.setFont(font)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.gridLayout_5.addWidget(self.line_19, 19, 0, 1, 3)
        self.label_adv_torqueMotor = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_torqueMotor.setFont(font)
        self.label_adv_torqueMotor.setObjectName(_fromUtf8("label_adv_torqueMotor"))
        self.gridLayout_5.addWidget(self.label_adv_torqueMotor, 10, 2, 1, 1)
        self.label_adv_RPM = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_RPM.setFont(font)
        self.label_adv_RPM.setObjectName(_fromUtf8("label_adv_RPM"))
        self.gridLayout_5.addWidget(self.label_adv_RPM, 6, 2, 1, 1)
        self.label_adv_torqueSensor = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_torqueSensor.setFont(font)
        self.label_adv_torqueSensor.setObjectName(_fromUtf8("label_adv_torqueSensor"))
        self.gridLayout_5.addWidget(self.label_adv_torqueSensor, 12, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_5.addWidget(self.label_47, 12, 0, 1, 1)
        self.line_15 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_15.setFont(font)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.gridLayout_5.addWidget(self.line_15, 13, 0, 1, 3)
        self.label_48 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_5.addWidget(self.label_48, 14, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_5.addWidget(self.label_44, 6, 0, 1, 1)
        self.line_16 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_16.setFont(font)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout_5.addWidget(self.line_16, 7, 0, 1, 3)
        self.label_adv_ROP3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_ROP3.setFont(font)
        self.label_adv_ROP3.setObjectName(_fromUtf8("label_adv_ROP3"))
        self.gridLayout_5.addWidget(self.label_adv_ROP3, 2, 2, 1, 1)
        self.line_12 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_12.setFont(font)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_5.addWidget(self.line_12, 11, 0, 1, 3)
        self.label_adv_WOB = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_WOB.setFont(font)
        self.label_adv_WOB.setObjectName(_fromUtf8("label_adv_WOB"))
        self.gridLayout_5.addWidget(self.label_adv_WOB, 8, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_5.addWidget(self.label_45, 8, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_5.addWidget(self.label_46, 10, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_14.setFont(font)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_5.addWidget(self.line_14, 9, 0, 1, 3)
        self.label_42 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 4, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_5.addWidget(self.label_43, 2, 0, 1, 1)
        self.line_13 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_13.setFont(font)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_5.addWidget(self.line_13, 3, 0, 1, 3)
        self.line_20 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_20.setFont(font)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.gridLayout_5.addWidget(self.line_20, 5, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(24, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.line_22 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_22.setFont(font)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.gridLayout_5.addWidget(self.line_22, 1, 0, 1, 3)
        self.label_adv_ROP15 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_adv_ROP15.setFont(font)
        self.label_adv_ROP15.setObjectName(_fromUtf8("label_adv_ROP15"))
        self.gridLayout_5.addWidget(self.label_adv_ROP15, 0, 2, 1, 1)
        self.label_95 = QtGui.QLabel(self.centralwidget)
        self.label_95.setGeometry(QtCore.QRect(560, 30, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_95.setFont(font)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(10, 740, 821, 20))
        self.line_10.setLineWidth(5)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_23 = QtGui.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(510, 5, 21, 741))
        self.line_23.setLineWidth(5)
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(1100, 1110, 211, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0,0,0,0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.radioButton_9 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setText(_fromUtf8(""))
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.gridLayout.addWidget(self.radioButton_9, 6, 4, 1, 1)
        self.label_103 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_103.sizePolicy().hasHeightForWidth())
        self.label_103.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_103.setFont(font)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout.addWidget(self.label_103, 5, 0, 1, 1)
        self.radioButton_15 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setText(_fromUtf8(""))
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.gridLayout.addWidget(self.radioButton_15, 5, 4, 1, 1)
        self.label_97 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_97.sizePolicy().hasHeightForWidth())
        self.label_97.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_97.setFont(font)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.gridLayout.addWidget(self.label_97, 6, 0, 1, 1)
        self.label_102 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_102.sizePolicy().hasHeightForWidth())
        self.label_102.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout.addWidget(self.label_102, 0, 0, 1, 1)
        self.radioButton_12 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setText(_fromUtf8(""))
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.gridLayout.addWidget(self.radioButton_12, 0, 4, 1, 1)
        self.radioButton_13 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setText(_fromUtf8(""))
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.gridLayout.addWidget(self.radioButton_13, 1, 4, 1, 1)
        self.label_100 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_100.sizePolicy().hasHeightForWidth())
        self.label_100.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_100.setFont(font)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout.addWidget(self.label_100, 1, 0, 1, 1)
        self.label_101 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_101.sizePolicy().hasHeightForWidth())
        self.label_101.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_101.setFont(font)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout.addWidget(self.label_101, 2, 0, 1, 1)
        self.radioButton_16 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_16.setFont(font)
        self.radioButton_16.setText(_fromUtf8(""))
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.gridLayout.addWidget(self.radioButton_16, 2, 4, 1, 1)
        self.label_99 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_99.sizePolicy().hasHeightForWidth())
        self.label_99.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_99.setFont(font)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout.addWidget(self.label_99, 3, 0, 1, 1)
        self.radioButton_10 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setText(_fromUtf8(""))
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.gridLayout.addWidget(self.radioButton_10, 3, 4, 1, 1)
        self.label_98 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_98.sizePolicy().hasHeightForWidth())
        self.label_98.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_98.setFont(font)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout.addWidget(self.label_98, 4, 0, 1, 1)
        self.radioButton_14 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setText(_fromUtf8(""))
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.gridLayout.addWidget(self.radioButton_14, 4, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.checkBox_adv_depthBased = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_adv_depthBased.setGeometry(QtCore.QRect(1340, 950, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_adv_depthBased.setFont(font)
        self.checkBox_adv_depthBased.setObjectName(_fromUtf8("checkBox_adv_depthBased"))
        self.label_53 = QtGui.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(1940, 1035, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setAccessibleName(_fromUtf8(""))
        self.label_53.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(1380, 1030, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAccessibleName(_fromUtf8(""))
        self.label_54.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_54.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(2180, 1030, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setAccessibleName(_fromUtf8(""))
        self.label_55.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_57 = QtGui.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(2670, 1030, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setAccessibleName(_fromUtf8(""))
        self.label_57.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_56 = QtGui.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(2400, 1030, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setAccessibleName(_fromUtf8(""))
        self.label_56.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_59 = QtGui.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(2970, 1030, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setAccessibleName(_fromUtf8(""))
        self.label_59.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_60 = QtGui.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(3230, 1030, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setAccessibleName(_fromUtf8(""))
        self.label_60.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_61 = QtGui.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(3500, 1030, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setAccessibleName(_fromUtf8(""))
        self.label_61.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(1630, 1030, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setAccessibleName(_fromUtf8(""))
        self.label_62.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1340, 1020, 2381, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(False)
        self.frame.setFont(font)
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(94, 13, 15);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tableWidget_adv_incidents = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_adv_incidents.setGeometry(QtCore.QRect(50, 790, 731, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_adv_incidents.setFont(font)
        self.tableWidget_adv_incidents.setObjectName(_fromUtf8("tableWidget_adv_incidents"))
        self.tableWidget_adv_incidents.setColumnCount(6)
        self.tableWidget_adv_incidents.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_adv_incidents.setHorizontalHeaderItem(5, item)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(530, 100, 281, 631))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_adv_TwistOff = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_TwistOff.setFont(font)
        self.label_adv_TwistOff.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_adv_TwistOff.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_TwistOff.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_TwistOff.setScaledContents(False)
        self.label_adv_TwistOff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_TwistOff.setWordWrap(False)
        self.label_adv_TwistOff.setObjectName(_fromUtf8("label_adv_TwistOff"))
        self.verticalLayout.addWidget(self.label_adv_TwistOff)
        self.label_adv_overTorque = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_overTorque.setFont(font)
        self.label_adv_overTorque.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_overTorque.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_overTorque.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_overTorque.setWordWrap(False)
        self.label_adv_overTorque.setObjectName(_fromUtf8("label_adv_overTorque"))
        self.verticalLayout.addWidget(self.label_adv_overTorque)
        self.label_adv_CriticalBuckling = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_CriticalBuckling.setFont(font)
        self.label_adv_CriticalBuckling.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_CriticalBuckling.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_CriticalBuckling.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_CriticalBuckling.setWordWrap(False)
        self.label_adv_CriticalBuckling.setObjectName(_fromUtf8("label_adv_CriticalBuckling"))
        self.verticalLayout.addWidget(self.label_adv_CriticalBuckling)
        self.label_adv_axialVib = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_axialVib.setFont(font)
        self.label_adv_axialVib.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_axialVib.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_axialVib.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_axialVib.setWordWrap(False)
        self.label_adv_axialVib.setObjectName(_fromUtf8("label_adv_axialVib"))
        self.verticalLayout.addWidget(self.label_adv_axialVib)
        self.label_adv_stickSlip = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_stickSlip.setFont(font)
        self.label_adv_stickSlip.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_stickSlip.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_stickSlip.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_stickSlip.setWordWrap(False)
        self.label_adv_stickSlip.setObjectName(_fromUtf8("label_adv_stickSlip"))
        self.verticalLayout.addWidget(self.label_adv_stickSlip)
        self.label_adv_lateralVib = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_lateralVib.setFont(font)
        self.label_adv_lateralVib.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_lateralVib.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_lateralVib.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_lateralVib.setWordWrap(False)
        self.label_adv_lateralVib.setObjectName(_fromUtf8("label_adv_lateralVib"))
        self.verticalLayout.addWidget(self.label_adv_lateralVib)
        self.label_adv_leak = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_leak.setFont(font)
        self.label_adv_leak.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_leak.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_leak.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_leak.setWordWrap(False)
        self.label_adv_leak.setObjectName(_fromUtf8("label_adv_leak"))
        self.verticalLayout.addWidget(self.label_adv_leak)
        self.label_adv_overpressure = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_overpressure.setFont(font)
        self.label_adv_overpressure.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_overpressure.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_overpressure.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_overpressure.setWordWrap(False)
        self.label_adv_overpressure.setObjectName(_fromUtf8("label_adv_overpressure"))
        self.verticalLayout.addWidget(self.label_adv_overpressure)
        self.label_adv_newForm = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_adv_newForm.setFont(font)
        self.label_adv_newForm.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_adv_newForm.setFrameShadow(QtGui.QFrame.Raised)
        self.label_adv_newForm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adv_newForm.setWordWrap(False)
        self.label_adv_newForm.setObjectName(_fromUtf8("label_adv_newForm"))
        self.verticalLayout.addWidget(self.label_adv_newForm)
        self.line_38 = QtGui.QFrame(self.centralwidget)
        self.line_38.setGeometry(QtCore.QRect(2804, 4, 21, 841))
        self.line_38.setLineWidth(5)
        self.line_38.setFrameShape(QtGui.QFrame.VLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.line_43 = QtGui.QFrame(self.centralwidget)
        self.line_43.setGeometry(QtCore.QRect(2520, 4, 21, 921))
        self.line_43.setLineWidth(5)
        self.line_43.setFrameShape(QtGui.QFrame.VLine)
        self.line_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_43.setObjectName(_fromUtf8("line_43"))
        self.progressBar_adv_UCS = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_adv_UCS.setGeometry(QtCore.QRect(1270, 850, 381, 31))
        self.progressBar_adv_UCS.setRange(0,175)
        #self.progressBar_adv_UCS.setProperty("value", 24)
        self.progressBar_adv_UCS.setObjectName(_fromUtf8("progressBar_adv_UCS"))
        self.progressBar_adv_MSE = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_adv_MSE.setGeometry(QtCore.QRect(850, 850, 381, 31))
        self.progressBar_adv_MSE.setRange(0,500)
        #self.progressBar_adv_MSE.setProperty("value", 24)
        self.progressBar_adv_MSE.setObjectName(_fromUtf8("progressBar_adv_MSE"))
        self.dial_adv_axialVib = QtGui.QDial(self.centralwidget)
        self.dial_adv_axialVib.setGeometry(QtCore.QRect(1600, 520, 581, 331))
        self.dial_adv_axialVib.setMinimum(-500)
        self.dial_adv_axialVib.setMaximum(500)
        self.dial_adv_axialVib.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_axialVib.setObjectName(_fromUtf8("dial_adv_axialVib"))
        self.dial_adv_UCS = QtGui.QDial(self.centralwidget)
        self.dial_adv_UCS.setGeometry(QtCore.QRect(1180, 520, 581, 331))
        self.dial_adv_UCS.setMinimum(0)
        self.dial_adv_UCS.setMaximum(175)
        self.dial_adv_UCS.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_UCS.setObjectName(_fromUtf8("dial_adv_UCS"))
        self.dial_adv_MSE = QtGui.QDial(self.centralwidget)
        self.dial_adv_MSE.setGeometry(QtCore.QRect(760, 520, 581, 331))
        self.dial_adv_MSE.setMinimum(0)
        self.dial_adv_MSE.setMaximum(500)
        self.dial_adv_MSE.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_MSE.setObjectName(_fromUtf8("dial_adv_MSE"))
        self.label_63 = QtGui.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(1340, 810, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(1560, 810, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_65 = QtGui.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(1720, 810, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(1980, 810, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(2180, 810, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_68 = QtGui.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(2400, 810, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.progressBar_adv_Pressure = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_adv_Pressure.setGeometry(QtCore.QRect(2110, 400, 381, 31))
        self.progressBar_adv_Pressure.setRange(0,50)
        #self.progressBar_adv_Pressure.setProperty("value", 24)
        self.progressBar_adv_Pressure.setObjectName(_fromUtf8("progressBar_adv_Pressure"))
        self.label_69 = QtGui.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(1150, 360, 62, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(2200, 19, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_70 = QtGui.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(930, 360, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(1830, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_71 = QtGui.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(1870, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_72 = QtGui.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(1560, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.progressBar_adv_torque = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_adv_torque.setGeometry(QtCore.QRect(1270, 400, 381, 31))
        self.progressBar_adv_torque.setRange(0,100)
        #self.progressBar_adv_torque.setProperty("value", 24)
        self.progressBar_adv_torque.setObjectName(_fromUtf8("progressBar_adv_torque"))
        self.label_73 = QtGui.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(2180, 360, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.dial_adv_pressure = QtGui.QDial(self.centralwidget)
        self.dial_adv_pressure.setGeometry(QtCore.QRect(2020, 60, 581, 331))
        self.dial_adv_pressure.setMinimum(0)
        self.dial_adv_pressure.setMaximum(50)
        self.dial_adv_pressure.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_pressure.setObjectName(_fromUtf8("dial_adv_pressure"))
        self.label_74 = QtGui.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(1340, 360, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_75 = QtGui.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(1980, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.progressBar_adv_RPM = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_adv_RPM.setGeometry(QtCore.QRect(850, 400, 381, 31))
        self.progressBar_adv_RPM.setRange(0,1500)
        #self.progressBar_adv_RPM.setProperty("value", 24)
        self.progressBar_adv_RPM.setObjectName(_fromUtf8("progressBar_adv_RPM"))
        self.dial_adv_torque = QtGui.QDial(self.centralwidget)
        self.dial_adv_torque.setGeometry(QtCore.QRect(1180, 70, 581, 331))
        self.dial_adv_torque.setMinimum(0)
        self.dial_adv_torque.setMaximum(100)
        self.dial_adv_torque.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_torque.setObjectName(_fromUtf8("dial_adv_torque"))
        self.label_76 = QtGui.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(1030, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.label_77 = QtGui.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(1760, 360, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.label_78 = QtGui.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(2400, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1400, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_79 = QtGui.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(2293, 55, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(1464, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.dial_adv_RPM = QtGui.QDial(self.centralwidget)
        self.dial_adv_RPM.setGeometry(QtCore.QRect(760, 70, 581, 331))
        self.dial_adv_RPM.setMinimum(0)
        self.dial_adv_RPM.setMaximum(1500)
        self.dial_adv_RPM.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_RPM.setObjectName(_fromUtf8("dial_adv_RPM"))
        self.progressBar_adv_WOB = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_adv_WOB.setGeometry(QtCore.QRect(1690, 400, 381, 31))
        self.progressBar_adv_WOB.setRange(0,20)
        #self.progressBar_adv_WOB.setProperty("value", 24)
        self.progressBar_adv_WOB.setObjectName(_fromUtf8("progressBar_adv_WOB"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(960, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.dial_adv_WOB = QtGui.QDial(self.centralwidget)
        self.dial_adv_WOB.setGeometry(QtCore.QRect(1600, 70, 581, 331))
        self.dial_adv_WOB.setMinimum(0)
        self.dial_adv_WOB.setMaximum(20)
        self.dial_adv_WOB.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_adv_WOB.setObjectName(_fromUtf8("dial_adv_WOB"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(1050, 927, 21, 1131))
        self.line_11.setLineWidth(5)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.graphicsView_adv_formation = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_formation.setGeometry(QtCore.QRect(3450, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_formation.setFont(font)
        self.graphicsView_adv_formation.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_formation.setObjectName(_fromUtf8("graphicsView_adv_formation"))
        self.graphicsView_adv_UCS = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_UCS.setGeometry(QtCore.QRect(3180, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_UCS.setFont(font)
        self.graphicsView_adv_UCS.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_UCS.setObjectName(_fromUtf8("graphicsView_adv_UCS"))
        self.graphicsView_adv_ROP = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_ROP.setGeometry(QtCore.QRect(2640, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_ROP.setFont(font)
        self.graphicsView_adv_ROP.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_ROP.setObjectName(_fromUtf8("graphicsView_adv_ROP"))
        self.graphicsView_adv_MSE = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_MSE.setGeometry(QtCore.QRect(2910, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_MSE.setFont(font)
        self.graphicsView_adv_MSE.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_MSE.setObjectName(_fromUtf8("graphicsView_adv_MSE"))
        self.graphicsView_adv_RPM = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_RPM.setGeometry(QtCore.QRect(1860, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_RPM.setFont(font)
        self.graphicsView_adv_RPM.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_RPM.setObjectName(_fromUtf8("graphicsView_adv_RPM"))
        self.graphicsView_adv_bitTorque = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_bitTorque.setGeometry(QtCore.QRect(1600, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_bitTorque.setFont(font)
        self.graphicsView_adv_bitTorque.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_bitTorque.setObjectName(_fromUtf8("graphicsView_adv_bitTorque"))
        self.graphicsView_adv_WOB = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_WOB.setGeometry(QtCore.QRect(2120, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_WOB.setFont(font)
        self.graphicsView_adv_WOB.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_WOB.setObjectName(_fromUtf8("graphicsView_adv_WOB"))
        self.graphicsView_adv_Pressure = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_Pressure.setGeometry(QtCore.QRect(2380, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_Pressure.setFont(font)
        self.graphicsView_adv_Pressure.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_Pressure.setObjectName(_fromUtf8("graphicsView_adv_Pressure"))
        self.graphicsView_adv_torque = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_adv_torque.setGeometry(QtCore.QRect(1340, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_adv_torque.setFont(font)
        self.graphicsView_adv_torque.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_adv_torque.setObjectName(_fromUtf8("graphicsView_adv_torque"))
        self.lcdNumber_adv_ControllerWOB = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_adv_ControllerWOB.setGeometry(QtCore.QRect(2550, 640, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_adv_ControllerWOB.setFont(font)
        self.lcdNumber_adv_ControllerWOB.setObjectName(_fromUtf8("lcdNumber_adv_ControllerWOB"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(2550, 600, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lcdNumber_adv_ControllerRPM = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_adv_ControllerRPM.setGeometry(QtCore.QRect(2550, 800, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_adv_ControllerRPM.setFont(font)
        self.lcdNumber_adv_ControllerRPM.setObjectName(_fromUtf8("lcdNumber_adv_ControllerRPM"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(2550, 760, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.frame.raise_()
        self.graphicsView_adv_RPMWOB.raise_()
        self.checkBox_adv_accessLiveFeed.raise_()
        self.graphicsView_adv_ROPStep.raise_()
        self.graphicsView_adv_MSEStep.raise_()
        self.label.raise_()
        self.line_3.raise_()
        self.line_6.raise_()
        self.dial_adv_ROP.raise_()
        self.label_6.raise_()
        self.dial_adv_flowRate.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.lcdNumber_adv_AvgROP.raise_()
        self.lcdNumber_adv_Duration.raise_()
        self.lcdNumber_WellTVD.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_30.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.progressBar_adv_axialVib.raise_()
        self.progressBar_adv_flowRate.raise_()
        self.label_41.raise_()
        self.layoutWidget.raise_()
        self.label_95.raise_()
        self.line_10.raise_()
        self.line_23.raise_()
        self.checkBox_adv_depthBased.raise_()
        self.line_2.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_57.raise_()
        self.label_56.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.tableWidget_adv_incidents.raise_()
        self.line_38.raise_()
        self.line_43.raise_()
        self.progressBar_adv_UCS.raise_()
        self.progressBar_adv_MSE.raise_()
        self.dial_adv_axialVib.raise_()
        self.dial_adv_UCS.raise_()
        self.dial_adv_MSE.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.label_65.raise_()
        self.label_66.raise_()
        self.label_67.raise_()
        self.label_68.raise_()
        self.progressBar_adv_Pressure.raise_()
        self.label_69.raise_()
        self.label_29.raise_()
        self.label_70.raise_()
        self.label_31.raise_()
        self.label_71.raise_()
        self.label_72.raise_()
        self.progressBar_adv_torque.raise_()
        self.label_73.raise_()
        self.dial_adv_pressure.raise_()
        self.label_74.raise_()
        self.label_75.raise_()
        self.progressBar_adv_RPM.raise_()
        self.dial_adv_torque.raise_()
        self.label_76.raise_()
        self.label_77.raise_()
        self.label_78.raise_()
        self.label_32.raise_()
        self.label_79.raise_()
        self.label_33.raise_()
        self.dial_adv_RPM.raise_()
        self.progressBar_adv_WOB.raise_()
        self.label_34.raise_()
        self.dial_adv_WOB.raise_()
        self.line_7.raise_()
        self.line_11.raise_()
        self.line_5.raise_()
        self.graphicsView_adv_formation.raise_()
        self.graphicsView_adv_UCS.raise_()
        self.graphicsView_adv_ROP.raise_()
        self.graphicsView_adv_MSE.raise_()
        self.graphicsView_adv_RPM.raise_()
        self.graphicsView_adv_bitTorque.raise_()
        self.graphicsView_adv_WOB.raise_()
        self.graphicsView_adv_Pressure.raise_()
        self.graphicsView_adv_torque.raise_()
        self.lcdNumber_adv_ControllerWOB.raise_()
        self.label_17.raise_()
        self.lcdNumber_adv_ControllerRPM.raise_()
        self.label_18.raise_()
        self.line_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3859, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.checkBox_adv_accessLiveFeed.setText(_translate("MainWindow", "Access Live Feed", None))
        self.label.setText(_translate("MainWindow", "Rig Monitor:", None))
        self.label_6.setText(_translate("MainWindow", "ROP [mm/min]:", None))
        self.label_7.setText(_translate("MainWindow", "UCS [MPa]", None))
        self.label_8.setText(_translate("MainWindow", "Flow Rate [LPM]", None))
        self.label_9.setText(_translate("MainWindow", "MSE [MPa]", None))
        self.label_10.setText(_translate("MainWindow", "Axial Vibration [N]", None))
        self.label_11.setText(_translate("MainWindow", "Avg. ROP:", None))
        self.label_12.setText(_translate("MainWindow", "Well - TVD [cm]:", None))
        self.label_13.setText(_translate("MainWindow", "Duration [min]:", None))
        self.label_14.setText(_translate("MainWindow", "0", None))
        self.label_15.setText(_translate("MainWindow", "50", None))
        self.label_16.setText(_translate("MainWindow", "25", None))
        self.label_30.setText(_translate("MainWindow", "87.5", None))
        self.label_36.setText(_translate("MainWindow", "0", None))
        self.label_37.setText(_translate("MainWindow", "0", None))
        self.label_38.setText(_translate("MainWindow", "500", None))
        self.label_39.setText(_translate("MainWindow", "10", None))
        self.label_40.setText(_translate("MainWindow", "250", None))
        self.label_41.setText(_translate("MainWindow", "Well Log:", None))
        self.label_adv_Velocity.setText(_translate("MainWindow", "0", None))
        self.label_adv_stepCounter.setText(_translate("MainWindow", "0", None))
        self.label_adv_flowRate.setText(_translate("MainWindow", "0", None))
        self.label_adv_Pressure.setText(_translate("MainWindow", "0", None))
        self.label_51.setText(_translate("MainWindow", "Height-sensor [cm]", None))
        self.label_adv_Height.setText(_translate("MainWindow", "0", None))
        self.label_52.setText(_translate("MainWindow", "Instantanious ROP [mm/s]", None))
        self.label_50.setText(_translate("MainWindow", "Stepcounter [mm]", None))
        self.label_49.setText(_translate("MainWindow", "Flow Rate Q [LPM]", None))
        self.label_adv_torqueMotor.setText(_translate("MainWindow", "0", None))
        self.label_adv_RPM.setText(_translate("MainWindow", "0", None))
        self.label_adv_torqueSensor.setText(_translate("MainWindow", "0", None))
        self.label_47.setText(_translate("MainWindow", "TAM Torque [Nm]", None))
        self.label_48.setText(_translate("MainWindow", "Pressure [barA]", None))
        self.label_44.setText(_translate("MainWindow", "RPM [mm/s]", None))
        self.label_adv_ROP3.setText(_translate("MainWindow", "0", None))
        self.label_adv_WOB.setText(_translate("MainWindow", "0", None))
        self.label_45.setText(_translate("MainWindow", "WOB [kg]", None))
        self.label_46.setText(_translate("MainWindow", "Topdrive Torque [Nm]", None))
        self.label_42.setText(_translate("MainWindow", "Velocity [mm/s]", None))
        self.label_43.setText(_translate("MainWindow", "Average ROP [mm/s]", None))
        self.label_adv_ROP15.setText(_translate("MainWindow", "0", None))
        self.label_95.setText(_translate("MainWindow", "Incidents:", None))
        self.label_103.setText(_translate("MainWindow", "37.5cm", None))
        self.label_97.setText(_translate("MainWindow", "45cm", None))
        self.label_102.setText(_translate("MainWindow", "0cm", None))
        self.label_100.setText(_translate("MainWindow", "7.5cm", None))
        self.label_101.setText(_translate("MainWindow", "15cm", None))
        self.label_99.setText(_translate("MainWindow", "22.5cm", None))
        self.label_98.setText(_translate("MainWindow", "30cm", None))
        self.checkBox_adv_depthBased.setText(_translate("MainWindow", "Depth-based", None))
        self.label_53.setText(_translate("MainWindow", "RPM:", None))
        self.label_54.setText(_translate("MainWindow", "TORQUE [Nm]:", None))
        self.label_55.setText(_translate("MainWindow", "WOB [kg]:", None))
        self.label_57.setText(_translate("MainWindow", "ROP [mm/min]:", None))
        self.label_56.setText(_translate("MainWindow", "Pressure [barA]:", None))
        self.label_59.setText(_translate("MainWindow", "MSE [MPa]:", None))
        self.label_60.setText(_translate("MainWindow", "UCS [MPa]:", None))
        self.label_61.setText(_translate("MainWindow", "Formation:", None))
        self.label_62.setText(_translate("MainWindow", "BIT TORQUE [Nm]:", None))
        item = self.tableWidget_adv_incidents.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Incident:", None))
        item = self.tableWidget_adv_incidents.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "# of occurance:", None))
        item = self.tableWidget_adv_incidents.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time:", None))
        item = self.tableWidget_adv_incidents.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Over-Torque:", None))
        item = self.tableWidget_adv_incidents.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Buckling:", None))
        item = self.tableWidget_adv_incidents.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Axial Vib.:", None))
        item = self.tableWidget_adv_incidents.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Torsional Vibrations", None))
        item = self.tableWidget_adv_incidents.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Lateral Vib.:", None))
        item = self.tableWidget_adv_incidents.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Formation:", None))
        self.label_adv_TwistOff.setText(_translate("MainWindow", "Twist-Off", None))
        self.label_adv_overTorque.setText(_translate("MainWindow", "Over-Torque", None))
        self.label_adv_CriticalBuckling.setText(_translate("MainWindow", "Critical Buckling", None))
        self.label_adv_axialVib.setText(_translate("MainWindow", "Axial Vibration", None))
        self.label_adv_stickSlip.setText(_translate("MainWindow", "Torsional Vibrations", None))
        self.label_adv_lateralVib.setText(_translate("MainWindow", "Lateral Vibration", None))
        self.label_adv_leak.setText(_translate("MainWindow", "Leak", None))
        self.label_adv_overpressure.setText(_translate("MainWindow", "Overpressure", None))
        self.label_adv_newForm.setText(_translate("MainWindow", "New Formation", None))
        self.label_63.setText(_translate("MainWindow", "0", None))
        self.label_64.setText(_translate("MainWindow", "175", None))
        self.label_65.setText(_translate("MainWindow", "-500", None))
        self.label_66.setText(_translate("MainWindow", "500", None))
        self.label_67.setText(_translate("MainWindow", "0", None))
        self.label_68.setText(_translate("MainWindow", "20", None))
        self.label_69.setText(_translate("MainWindow", "1500", None))
        self.label_29.setText(_translate("MainWindow", "Pressure [barA]", None))
        self.label_70.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "WOB [kg]", None))
        self.label_71.setText(_translate("MainWindow", "10", None))
        self.label_72.setText(_translate("MainWindow", "10", None))
        self.label_73.setText(_translate("MainWindow", "0", None))
        self.label_74.setText(_translate("MainWindow", "0", None))
        self.label_75.setText(_translate("MainWindow", "20", None))
        self.label_76.setText(_translate("MainWindow", "750", None))
        self.label_77.setText(_translate("MainWindow", "0", None))
        self.label_78.setText(_translate("MainWindow", "5", None))
        self.label_32.setText(_translate("MainWindow", "Torque [Nm]", None))
        self.label_79.setText(_translate("MainWindow", "2.5", None))
        self.label_33.setText(_translate("MainWindow", "5", None))
        self.label_34.setText(_translate("MainWindow", "RPM [rev/min]", None))
        self.label_17.setText(_translate("MainWindow", "Controller WOB-setpoint:", None))
        self.label_18.setText(_translate("MainWindow", "Controller RPM-setpoint:", None))


