# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualizationGUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(3859, 2160)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.openGLWidget_3 = QOpenGLWidget(self.centralwidget)
        self.openGLWidget_3.setGeometry(QtCore.QRect(40, 1050, 971, 621))
        self.openGLWidget_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.openGLWidget_3.setObjectName(_fromUtf8("openGLWidget_3"))
        self.openGLWidget_4 = QOpenGLWidget(self.centralwidget)
        self.openGLWidget_4.setGeometry(QtCore.QRect(400, 1690, 611, 361))
        self.openGLWidget_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.openGLWidget_4.setObjectName(_fromUtf8("openGLWidget_4"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(310, 980, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.openGLWidget_5 = QOpenGLWidget(self.centralwidget)
        self.openGLWidget_5.setGeometry(QtCore.QRect(40, 1690, 341, 361))
        self.openGLWidget_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.openGLWidget_5.setObjectName(_fromUtf8("openGLWidget_5"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 920, 3721, 20))
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 970, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 0, 21, 2061))
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(9, 2050, 3721, 21))
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(3720, 0, 21, 2061))
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, -3, 3721, 20))
        self.line_6.setLineWidth(5)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.dial_5 = QtGui.QDial(self.centralwidget)
        self.dial_5.setGeometry(QtCore.QRect(-110, 190, 741, 521))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dial_5.setFont(font)
        self.dial_5.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_5.setObjectName(_fromUtf8("dial_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 10, 421, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.dial_6 = QtGui.QDial(self.centralwidget)
        self.dial_6.setGeometry(QtCore.QRect(2020, 510, 581, 331))
        self.dial_6.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_6.setObjectName(_fromUtf8("dial_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1400, 470, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(2200, 469, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(990, 470, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1770, 470, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(821, 5, 21, 921))
        self.line_7.setLineWidth(5)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(2550, 450, 241, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(2550, 260, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(2550, 70, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(2552, 390, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(2550, 20, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(2552, 200, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(80, 655, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(390, 650, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(230, 160, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(1450, 510, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(930, 810, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(1870, 510, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(1150, 810, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(2270, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(1030, 510, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.progressBar_3 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(1690, 850, 381, 31))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.progressBar_4 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_4.setGeometry(QtCore.QRect(2110, 850, 381, 31))
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(1100, 950, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(2830, 10, 881, 831))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_Height_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_Height_5.setFont(font)
        self.label_Height_5.setObjectName(_fromUtf8("label_Height_5"))
        self.gridLayout_5.addWidget(self.label_Height_5, 20, 2, 1, 1)
        self.line_18 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_18.setFont(font)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.gridLayout_5.addWidget(self.line_18, 21, 0, 1, 3)
        self.label_MSE = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_MSE.setFont(font)
        self.label_MSE.setObjectName(_fromUtf8("label_MSE"))
        self.gridLayout_5.addWidget(self.label_MSE, 16, 2, 1, 1)
        self.line_21 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_21.setFont(font)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.gridLayout_5.addWidget(self.line_21, 17, 0, 1, 3)
        self.label_Pressure = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_Pressure.setFont(font)
        self.label_Pressure.setObjectName(_fromUtf8("label_Pressure"))
        self.gridLayout_5.addWidget(self.label_Pressure, 14, 2, 1, 1)
        self.label_51 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_5.addWidget(self.label_51, 18, 0, 1, 1)
        self.label_Height = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_Height.setFont(font)
        self.label_Height.setObjectName(_fromUtf8("label_Height"))
        self.gridLayout_5.addWidget(self.label_Height, 18, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_5.addWidget(self.label_52, 0, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_5.addWidget(self.label_50, 20, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_5.addWidget(self.label_49, 16, 0, 1, 1)
        self.line_17 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_17.setFont(font)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.gridLayout_5.addWidget(self.line_17, 15, 0, 1, 3)
        self.line_19 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_19.setFont(font)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.gridLayout_5.addWidget(self.line_19, 19, 0, 1, 3)
        self.label_Torque_Motor = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_Torque_Motor.setFont(font)
        self.label_Torque_Motor.setObjectName(_fromUtf8("label_Torque_Motor"))
        self.gridLayout_5.addWidget(self.label_Torque_Motor, 10, 2, 1, 1)
        self.label_RPM = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_RPM.setFont(font)
        self.label_RPM.setObjectName(_fromUtf8("label_RPM"))
        self.gridLayout_5.addWidget(self.label_RPM, 6, 2, 1, 1)
        self.label_Torque_Sensor = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_Torque_Sensor.setFont(font)
        self.label_Torque_Sensor.setObjectName(_fromUtf8("label_Torque_Sensor"))
        self.gridLayout_5.addWidget(self.label_Torque_Sensor, 12, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_5.addWidget(self.label_47, 12, 0, 1, 1)
        self.line_15 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_15.setFont(font)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.gridLayout_5.addWidget(self.line_15, 13, 0, 1, 3)
        self.label_48 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_5.addWidget(self.label_48, 14, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_5.addWidget(self.label_44, 6, 0, 1, 1)
        self.line_16 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_16.setFont(font)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout_5.addWidget(self.line_16, 7, 0, 1, 3)
        self.label_ROP3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_ROP3.setFont(font)
        self.label_ROP3.setObjectName(_fromUtf8("label_ROP3"))
        self.gridLayout_5.addWidget(self.label_ROP3, 2, 2, 1, 1)
        self.line_12 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_12.setFont(font)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_5.addWidget(self.line_12, 11, 0, 1, 3)
        self.label_WOB = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_WOB.setFont(font)
        self.label_WOB.setObjectName(_fromUtf8("label_WOB"))
        self.gridLayout_5.addWidget(self.label_WOB, 8, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_5.addWidget(self.label_45, 8, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_5.addWidget(self.label_46, 10, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_14.setFont(font)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_5.addWidget(self.line_14, 9, 0, 1, 3)
        self.label_42 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 4, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_5.addWidget(self.label_43, 2, 0, 1, 1)
        self.label_ROP15_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_ROP15_2.setFont(font)
        self.label_ROP15_2.setObjectName(_fromUtf8("label_ROP15_2"))
        self.gridLayout_5.addWidget(self.label_ROP15_2, 4, 2, 1, 1)
        self.line_13 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_13.setFont(font)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_5.addWidget(self.line_13, 3, 0, 1, 3)
        self.line_20 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_20.setFont(font)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.gridLayout_5.addWidget(self.line_20, 5, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(24, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.label_ROP15 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_ROP15.setFont(font)
        self.label_ROP15.setObjectName(_fromUtf8("label_ROP15"))
        self.gridLayout_5.addWidget(self.label_ROP15, 0, 2, 1, 1)
        self.line_22 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_22.setFont(font)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.gridLayout_5.addWidget(self.line_22, 1, 0, 1, 3)
        self.label_95 = QtGui.QLabel(self.centralwidget)
        self.label_95.setGeometry(QtCore.QRect(560, 30, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_95.setFont(font)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(10, 740, 821, 20))
        self.line_10.setLineWidth(5)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_23 = QtGui.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(510, 5, 21, 741))
        self.line_23.setLineWidth(5)
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(1100, 1110, 211, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.radioButton_9 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setText(_fromUtf8(""))
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.gridLayout.addWidget(self.radioButton_9, 6, 4, 1, 1)
        self.label_103 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_103.sizePolicy().hasHeightForWidth())
        self.label_103.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_103.setFont(font)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout.addWidget(self.label_103, 5, 0, 1, 1)
        self.radioButton_15 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setText(_fromUtf8(""))
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.gridLayout.addWidget(self.radioButton_15, 5, 4, 1, 1)
        self.label_97 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_97.sizePolicy().hasHeightForWidth())
        self.label_97.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_97.setFont(font)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.gridLayout.addWidget(self.label_97, 6, 0, 1, 1)
        self.label_102 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_102.sizePolicy().hasHeightForWidth())
        self.label_102.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout.addWidget(self.label_102, 0, 0, 1, 1)
        self.radioButton_12 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setText(_fromUtf8(""))
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.gridLayout.addWidget(self.radioButton_12, 0, 4, 1, 1)
        self.radioButton_13 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setText(_fromUtf8(""))
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.gridLayout.addWidget(self.radioButton_13, 1, 4, 1, 1)
        self.label_100 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_100.sizePolicy().hasHeightForWidth())
        self.label_100.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_100.setFont(font)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout.addWidget(self.label_100, 1, 0, 1, 1)
        self.label_101 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_101.sizePolicy().hasHeightForWidth())
        self.label_101.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_101.setFont(font)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout.addWidget(self.label_101, 2, 0, 1, 1)
        self.radioButton_16 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_16.setFont(font)
        self.radioButton_16.setText(_fromUtf8(""))
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.gridLayout.addWidget(self.radioButton_16, 2, 4, 1, 1)
        self.label_99 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_99.sizePolicy().hasHeightForWidth())
        self.label_99.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_99.setFont(font)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout.addWidget(self.label_99, 3, 0, 1, 1)
        self.radioButton_10 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setText(_fromUtf8(""))
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.gridLayout.addWidget(self.radioButton_10, 3, 4, 1, 1)
        self.label_98 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_98.sizePolicy().hasHeightForWidth())
        self.label_98.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_98.setFont(font)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout.addWidget(self.label_98, 4, 0, 1, 1)
        self.radioButton_14 = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setText(_fromUtf8(""))
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.gridLayout.addWidget(self.radioButton_14, 4, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(1340, 950, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.label_53 = QtGui.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(1940, 1035, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setAccessibleName(_fromUtf8(""))
        self.label_53.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(1380, 1030, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAccessibleName(_fromUtf8(""))
        self.label_54.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_54.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(2180, 1030, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setAccessibleName(_fromUtf8(""))
        self.label_55.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_57 = QtGui.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(2670, 1030, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setAccessibleName(_fromUtf8(""))
        self.label_57.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_56 = QtGui.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(2400, 1030, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setAccessibleName(_fromUtf8(""))
        self.label_56.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_59 = QtGui.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(2970, 1030, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setAccessibleName(_fromUtf8(""))
        self.label_59.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_60 = QtGui.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(3230, 1030, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setAccessibleName(_fromUtf8(""))
        self.label_60.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_61 = QtGui.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(3500, 1030, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setAccessibleName(_fromUtf8(""))
        self.label_61.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(1630, 1030, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setAccessibleName(_fromUtf8(""))
        self.label_62.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1340, 1020, 2381, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(False)
        self.frame.setFont(font)
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(94, 13, 15);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 790, 731, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(530, 100, 281, 631))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_Stopped_8 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_8.setFont(font)
        self.label_Stopped_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Stopped_8.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_8.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_8.setScaledContents(False)
        self.label_Stopped_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_8.setWordWrap(False)
        self.label_Stopped_8.setObjectName(_fromUtf8("label_Stopped_8"))
        self.verticalLayout.addWidget(self.label_Stopped_8)
        self.label_Stopped_7 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_7.setFont(font)
        self.label_Stopped_7.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_7.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_7.setWordWrap(False)
        self.label_Stopped_7.setObjectName(_fromUtf8("label_Stopped_7"))
        self.verticalLayout.addWidget(self.label_Stopped_7)
        self.label_Stopped_6 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_6.setFont(font)
        self.label_Stopped_6.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_6.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_6.setWordWrap(False)
        self.label_Stopped_6.setObjectName(_fromUtf8("label_Stopped_6"))
        self.verticalLayout.addWidget(self.label_Stopped_6)
        self.label_Stopped_3 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_3.setFont(font)
        self.label_Stopped_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_3.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_3.setWordWrap(False)
        self.label_Stopped_3.setObjectName(_fromUtf8("label_Stopped_3"))
        self.verticalLayout.addWidget(self.label_Stopped_3)
        self.label_Stopped_5 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_5.setFont(font)
        self.label_Stopped_5.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_5.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_5.setWordWrap(False)
        self.label_Stopped_5.setObjectName(_fromUtf8("label_Stopped_5"))
        self.verticalLayout.addWidget(self.label_Stopped_5)
        self.label_Stopped_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_4.setFont(font)
        self.label_Stopped_4.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_4.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_4.setWordWrap(False)
        self.label_Stopped_4.setObjectName(_fromUtf8("label_Stopped_4"))
        self.verticalLayout.addWidget(self.label_Stopped_4)
        self.label_Stopped_11 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_11.setFont(font)
        self.label_Stopped_11.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_11.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_11.setWordWrap(False)
        self.label_Stopped_11.setObjectName(_fromUtf8("label_Stopped_11"))
        self.verticalLayout.addWidget(self.label_Stopped_11)
        self.label_Stopped_10 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_10.setFont(font)
        self.label_Stopped_10.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_10.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_10.setWordWrap(False)
        self.label_Stopped_10.setObjectName(_fromUtf8("label_Stopped_10"))
        self.verticalLayout.addWidget(self.label_Stopped_10)
        self.label_Stopped_9 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Stopped_9.setFont(font)
        self.label_Stopped_9.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Stopped_9.setFrameShadow(QtGui.QFrame.Raised)
        self.label_Stopped_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stopped_9.setWordWrap(False)
        self.label_Stopped_9.setObjectName(_fromUtf8("label_Stopped_9"))
        self.verticalLayout.addWidget(self.label_Stopped_9)
        self.line_38 = QtGui.QFrame(self.centralwidget)
        self.line_38.setGeometry(QtCore.QRect(2804, 4, 21, 841))
        self.line_38.setLineWidth(5)
        self.line_38.setFrameShape(QtGui.QFrame.VLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.line_43 = QtGui.QFrame(self.centralwidget)
        self.line_43.setGeometry(QtCore.QRect(2520, 4, 21, 921))
        self.line_43.setLineWidth(5)
        self.line_43.setFrameShape(QtGui.QFrame.VLine)
        self.line_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_43.setObjectName(_fromUtf8("line_43"))
        self.progressBar_9 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_9.setGeometry(QtCore.QRect(1270, 850, 381, 31))
        self.progressBar_9.setProperty("value", 24)
        self.progressBar_9.setObjectName(_fromUtf8("progressBar_9"))
        self.progressBar_10 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_10.setGeometry(QtCore.QRect(850, 850, 381, 31))
        self.progressBar_10.setProperty("value", 24)
        self.progressBar_10.setObjectName(_fromUtf8("progressBar_10"))
        self.dial_7 = QtGui.QDial(self.centralwidget)
        self.dial_7.setGeometry(QtCore.QRect(1600, 520, 581, 331))
        self.dial_7.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_7.setObjectName(_fromUtf8("dial_7"))
        self.dial_8 = QtGui.QDial(self.centralwidget)
        self.dial_8.setGeometry(QtCore.QRect(1180, 520, 581, 331))
        self.dial_8.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_8.setObjectName(_fromUtf8("dial_8"))
        self.dial_9 = QtGui.QDial(self.centralwidget)
        self.dial_9.setGeometry(QtCore.QRect(760, 520, 581, 331))
        self.dial_9.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_9.setObjectName(_fromUtf8("dial_9"))
        self.label_63 = QtGui.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(1340, 810, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(1560, 810, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_65 = QtGui.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(1760, 810, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(1980, 810, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(2180, 810, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_68 = QtGui.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(2400, 810, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.progressBar_11 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_11.setGeometry(QtCore.QRect(2110, 400, 381, 31))
        self.progressBar_11.setProperty("value", 24)
        self.progressBar_11.setObjectName(_fromUtf8("progressBar_11"))
        self.label_69 = QtGui.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(1150, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(2200, 19, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_70 = QtGui.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(930, 360, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(1830, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_71 = QtGui.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(1870, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_72 = QtGui.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(1560, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.progressBar_12 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_12.setGeometry(QtCore.QRect(1270, 400, 381, 31))
        self.progressBar_12.setProperty("value", 24)
        self.progressBar_12.setObjectName(_fromUtf8("progressBar_12"))
        self.label_73 = QtGui.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(2180, 360, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.dial_10 = QtGui.QDial(self.centralwidget)
        self.dial_10.setGeometry(QtCore.QRect(2020, 60, 581, 331))
        self.dial_10.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_10.setObjectName(_fromUtf8("dial_10"))
        self.label_74 = QtGui.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(1340, 360, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_75 = QtGui.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(1980, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.progressBar_13 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_13.setGeometry(QtCore.QRect(850, 400, 381, 31))
        self.progressBar_13.setProperty("value", 24)
        self.progressBar_13.setObjectName(_fromUtf8("progressBar_13"))
        self.dial_11 = QtGui.QDial(self.centralwidget)
        self.dial_11.setGeometry(QtCore.QRect(1180, 70, 581, 331))
        self.dial_11.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_11.setObjectName(_fromUtf8("dial_11"))
        self.label_76 = QtGui.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(1030, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.label_77 = QtGui.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(1760, 360, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.label_78 = QtGui.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(2400, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1400, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_79 = QtGui.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(2270, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(1440, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.dial_12 = QtGui.QDial(self.centralwidget)
        self.dial_12.setGeometry(QtCore.QRect(760, 70, 581, 331))
        self.dial_12.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_12.setObjectName(_fromUtf8("dial_12"))
        self.progressBar_14 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_14.setGeometry(QtCore.QRect(1690, 400, 381, 31))
        self.progressBar_14.setProperty("value", 24)
        self.progressBar_14.setObjectName(_fromUtf8("progressBar_14"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(960, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.dial_13 = QtGui.QDial(self.centralwidget)
        self.dial_13.setGeometry(QtCore.QRect(1600, 70, 581, 331))
        self.dial_13.setStyleSheet(_fromUtf8("background-color: rgb(83, 1, 1);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.dial_13.setObjectName(_fromUtf8("dial_13"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(1050, 927, 21, 1131))
        self.line_11.setLineWidth(5)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.graphicsView_6 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_6.setGeometry(QtCore.QRect(3450, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_6.setFont(font)
        self.graphicsView_6.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_6.setObjectName(_fromUtf8("graphicsView_6"))
        self.graphicsView_7 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_7.setGeometry(QtCore.QRect(3180, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_7.setFont(font)
        self.graphicsView_7.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_7.setObjectName(_fromUtf8("graphicsView_7"))
        self.graphicsView_8 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_8.setGeometry(QtCore.QRect(2640, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_8.setFont(font)
        self.graphicsView_8.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_8.setObjectName(_fromUtf8("graphicsView_8"))
        self.graphicsView_9 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_9.setGeometry(QtCore.QRect(2910, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_9.setFont(font)
        self.graphicsView_9.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_9.setObjectName(_fromUtf8("graphicsView_9"))
        self.graphicsView_10 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_10.setGeometry(QtCore.QRect(1860, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_10.setFont(font)
        self.graphicsView_10.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_10.setObjectName(_fromUtf8("graphicsView_10"))
        self.graphicsView_11 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_11.setGeometry(QtCore.QRect(1600, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_11.setFont(font)
        self.graphicsView_11.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_11.setObjectName(_fromUtf8("graphicsView_11"))
        self.graphicsView_12 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_12.setGeometry(QtCore.QRect(2120, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_12.setFont(font)
        self.graphicsView_12.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_12.setObjectName(_fromUtf8("graphicsView_12"))
        self.graphicsView_13 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_13.setGeometry(QtCore.QRect(2380, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_13.setFont(font)
        self.graphicsView_13.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_13.setObjectName(_fromUtf8("graphicsView_13"))
        self.graphicsView_14 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_14.setGeometry(QtCore.QRect(1340, 1110, 251, 931))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.graphicsView_14.setFont(font)
        self.graphicsView_14.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.graphicsView_14.setObjectName(_fromUtf8("graphicsView_14"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(2550, 640, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(2550, 600, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lcdNumber_5 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(2550, 800, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(2550, 760, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.frame.raise_()
        self.openGLWidget_3.raise_()
        self.openGLWidget_4.raise_()
        self.checkBox.raise_()
        self.openGLWidget_5.raise_()
        self.label.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_6.raise_()
        self.dial_5.raise_()
        self.label_6.raise_()
        self.dial_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        self.lcdNumber_3.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_30.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.progressBar_3.raise_()
        self.progressBar_4.raise_()
        self.label_41.raise_()
        self.layoutWidget.raise_()
        self.label_95.raise_()
        self.line_10.raise_()
        self.line_23.raise_()
        self.checkBox_2.raise_()
        self.line_2.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_57.raise_()
        self.label_56.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.tableWidget.raise_()
        self.line_38.raise_()
        self.line_43.raise_()
        self.progressBar_9.raise_()
        self.progressBar_10.raise_()
        self.dial_7.raise_()
        self.dial_8.raise_()
        self.dial_9.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.label_65.raise_()
        self.label_66.raise_()
        self.label_67.raise_()
        self.label_68.raise_()
        self.progressBar_11.raise_()
        self.label_69.raise_()
        self.label_29.raise_()
        self.label_70.raise_()
        self.label_31.raise_()
        self.label_71.raise_()
        self.label_72.raise_()
        self.progressBar_12.raise_()
        self.label_73.raise_()
        self.dial_10.raise_()
        self.label_74.raise_()
        self.label_75.raise_()
        self.progressBar_13.raise_()
        self.dial_11.raise_()
        self.label_76.raise_()
        self.label_77.raise_()
        self.label_78.raise_()
        self.label_32.raise_()
        self.label_79.raise_()
        self.label_33.raise_()
        self.dial_12.raise_()
        self.progressBar_14.raise_()
        self.label_34.raise_()
        self.dial_13.raise_()
        self.line_7.raise_()
        self.line_11.raise_()
        self.line_5.raise_()
        self.graphicsView_6.raise_()
        self.graphicsView_7.raise_()
        self.graphicsView_8.raise_()
        self.graphicsView_9.raise_()
        self.graphicsView_10.raise_()
        self.graphicsView_11.raise_()
        self.graphicsView_12.raise_()
        self.graphicsView_13.raise_()
        self.graphicsView_14.raise_()
        self.lcdNumber_4.raise_()
        self.label_17.raise_()
        self.lcdNumber_5.raise_()
        self.label_18.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3859, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.checkBox.setText(_translate("MainWindow", "Access Live Feed", None))
        self.label.setText(_translate("MainWindow", "Camera Live Feed:", None))
        self.label_6.setText(_translate("MainWindow", "ROP [mm/min]:", None))
        self.label_7.setText(_translate("MainWindow", "UCS [MPa]", None))
        self.label_8.setText(_translate("MainWindow", "Bit Torque [Nm]", None))
        self.label_9.setText(_translate("MainWindow", "MSE [MPa]", None))
        self.label_10.setText(_translate("MainWindow", "Axial Vibration [N]", None))
        self.label_11.setText(_translate("MainWindow", "Avg. ROP:", None))
        self.label_12.setText(_translate("MainWindow", "Well - TVD [m]:", None))
        self.label_13.setText(_translate("MainWindow", "Duration [s]:", None))
        self.label_14.setText(_translate("MainWindow", "0", None))
        self.label_15.setText(_translate("MainWindow", "50", None))
        self.label_16.setText(_translate("MainWindow", "25", None))
        self.label_30.setText(_translate("MainWindow", "87.5", None))
        self.label_36.setText(_translate("MainWindow", "0", None))
        self.label_37.setText(_translate("MainWindow", "100", None))
        self.label_38.setText(_translate("MainWindow", "500", None))
        self.label_39.setText(_translate("MainWindow", "4.295", None))
        self.label_40.setText(_translate("MainWindow", "250", None))
        self.label_41.setText(_translate("MainWindow", "Well Log:", None))
        self.label_Height_5.setText(_translate("MainWindow", "0", None))
        self.label_MSE.setText(_translate("MainWindow", "0", None))
        self.label_Pressure.setText(_translate("MainWindow", "0", None))
        self.label_51.setText(_translate("MainWindow", "Height-sensor [cm]", None))
        self.label_Height.setText(_translate("MainWindow", "0", None))
        self.label_52.setText(_translate("MainWindow", "Instantanious ROP [mm/s]", None))
        self.label_50.setText(_translate("MainWindow", "Stepcounter [mm]", None))
        self.label_49.setText(_translate("MainWindow", "Flow Rate Q [LPM]", None))
        self.label_Torque_Motor.setText(_translate("MainWindow", "0", None))
        self.label_RPM.setText(_translate("MainWindow", "0", None))
        self.label_Torque_Sensor.setText(_translate("MainWindow", "0", None))
        self.label_47.setText(_translate("MainWindow", "TAM Torque [Nm]", None))
        self.label_48.setText(_translate("MainWindow", "Pressure [barA]", None))
        self.label_44.setText(_translate("MainWindow", "RPM [mm/s]", None))
        self.label_ROP3.setText(_translate("MainWindow", "0", None))
        self.label_WOB.setText(_translate("MainWindow", "0", None))
        self.label_45.setText(_translate("MainWindow", "WOB [kg]", None))
        self.label_46.setText(_translate("MainWindow", "Topdrive Torque [Nm]", None))
        self.label_42.setText(_translate("MainWindow", "Velocity [mm/s]", None))
        self.label_43.setText(_translate("MainWindow", "Average ROP [mm/s]", None))
        self.label_ROP15_2.setText(_translate("MainWindow", "0", None))
        self.label_ROP15.setText(_translate("MainWindow", "0", None))
        self.label_95.setText(_translate("MainWindow", "Incidents:", None))
        self.label_103.setText(_translate("MainWindow", "50cm", None))
        self.label_97.setText(_translate("MainWindow", "60cm", None))
        self.label_102.setText(_translate("MainWindow", "0cm", None))
        self.label_100.setText(_translate("MainWindow", "10cm", None))
        self.label_101.setText(_translate("MainWindow", "20cm", None))
        self.label_99.setText(_translate("MainWindow", "30cm", None))
        self.label_98.setText(_translate("MainWindow", "40cm", None))
        self.checkBox_2.setText(_translate("MainWindow", "Depth-based", None))
        self.label_53.setText(_translate("MainWindow", "RPM:", None))
        self.label_54.setText(_translate("MainWindow", "TORQUE [Nm]:", None))
        self.label_55.setText(_translate("MainWindow", "WOB [kg]:", None))
        self.label_57.setText(_translate("MainWindow", "ROP [mm/min]:", None))
        self.label_56.setText(_translate("MainWindow", "Pressure [barA]:", None))
        self.label_59.setText(_translate("MainWindow", "MSE [MPa]:", None))
        self.label_60.setText(_translate("MainWindow", "UCS [MPa]:", None))
        self.label_61.setText(_translate("MainWindow", "Formation:", None))
        self.label_62.setText(_translate("MainWindow", "BIT TORQUE [Nm]:", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Incident:", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "# of occurance:", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time:", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Over-Torque:", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Buckling:", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Axial Vib.:", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Stick-Slip:", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Lateral Vib.:", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Formation:", None))
        self.label_Stopped_8.setText(_translate("MainWindow", "Twist-Off", None))
        self.label_Stopped_7.setText(_translate("MainWindow", "Over-Torque", None))
        self.label_Stopped_6.setText(_translate("MainWindow", "Critical Buckling", None))
        self.label_Stopped_3.setText(_translate("MainWindow", "Axial Vibration", None))
        self.label_Stopped_5.setText(_translate("MainWindow", "Stick-Slip", None))
        self.label_Stopped_4.setText(_translate("MainWindow", "Lateral Vibration", None))
        self.label_Stopped_11.setText(_translate("MainWindow", "Leak", None))
        self.label_Stopped_10.setText(_translate("MainWindow", "Overpressure", None))
        self.label_Stopped_9.setText(_translate("MainWindow", "New Formation", None))
        self.label_63.setText(_translate("MainWindow", "0", None))
        self.label_64.setText(_translate("MainWindow", "175", None))
        self.label_65.setText(_translate("MainWindow", "0", None))
        self.label_66.setText(_translate("MainWindow", "200", None))
        self.label_67.setText(_translate("MainWindow", "0", None))
        self.label_68.setText(_translate("MainWindow", "8.59", None))
        self.label_69.setText(_translate("MainWindow", "1400", None))
        self.label_29.setText(_translate("MainWindow", "Pressure [barA]", None))
        self.label_70.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "WOB [kg]", None))
        self.label_71.setText(_translate("MainWindow", "10", None))
        self.label_72.setText(_translate("MainWindow", "8.59", None))
        self.label_73.setText(_translate("MainWindow", "0", None))
        self.label_74.setText(_translate("MainWindow", "0", None))
        self.label_75.setText(_translate("MainWindow", "20", None))
        self.label_76.setText(_translate("MainWindow", "700", None))
        self.label_77.setText(_translate("MainWindow", "0", None))
        self.label_78.setText(_translate("MainWindow", "4.1", None))
        self.label_32.setText(_translate("MainWindow", "Torque [Nm]", None))
        self.label_79.setText(_translate("MainWindow", "2.05", None))
        self.label_33.setText(_translate("MainWindow", "4.925", None))
        self.label_34.setText(_translate("MainWindow", "RPM [rev/min]", None))
        self.label_17.setText(_translate("MainWindow", "Controller WOB-setpoint:", None))
        self.label_18.setText(_translate("MainWindow", "Controller RPM-setpoint:", None))

from qopenglwidget import QOpenGLWidget
